[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Challenges

# Custom rules
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if v.pinned then _joker.pinned = true end"
position = 'after'
match_indent = true
payload = '''
if v.joy_summoned then
    if JoyousSpring.is_monster_card(_joker) and JoyousSpring.has_joyous_table(_joker) then
        _joker.ability.extra.joyous_spring.summoned = true
    end
end
if v.joy_revived then
    if JoyousSpring.is_monster_card(_joker) and JoyousSpring.has_joyous_table(_joker) then
        _joker.ability.extra.joyous_spring.revived = true
    end
end
'''

# Temp fix for SMODS.add_to_pool because I'm stupid
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = '''
if v.in_pool and type(v.in_pool) == 'function' then
    add = in_pool and (add or pool_opts.override_base_checks)
end
'''
position = 'at'
match_indent = true
payload = '''
add = in_pool and (add or pool_opts.override_base_checks)
'''
